<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        \DB::table('orders')->delete();
        
        \DB::table('orders')->insert(array (
            0 =>
            array (
                'id' => 1,
                'order_number' => 'ERYARP20211231102832R1',
                'amount' => '9700',
                'sub_total' => '9700',
                'total_add_on' => '194',
                'total_shipping' => '8',
                'voucher_amount' => '0',
                'wallet_type' => '2',
                'receiver_name' => 'Test Merchant',
                'receiver_phone' => '6012345667',
                'receiver_address_1' => '11 aaa',
                'receiver_address_2' => NULL,
                'receiver_city' => 'Test City',
                'receiver_state' => 'Johor',
                'receiver_postcode' => '12345',
                'pre_point_balance' => '10000',
                'post_point_balance' => '300',
                'collect_type' => '2',
                'tracking_code' => NULL,
                'shipout_at' => NULL,
                'pickup_at' => NULL,
                'completed_at' => NULL,
                'refund_at' => NULL,
                'status' => '1',
                'remark' => NULL,
                'invoice_number' => NULL,
                'created_at' => '2021-12-31 10:28:31',
                'updated_at' => '2021-12-31 10:28:32',
                'deleted_at' => NULL,
                'user_id' => '5',
                'payment_method_id' => '4',
                'pickup_location_id' => NULL,
                'shipped_by_id' => NULL,
                'picked_up_by_id' => NULL,
                'completed_by_id' => NULL,
                'refund_by_id' => NULL,
                'shipping_company_id' => NULL,
                'invoice_user_id' => '5',
                'order_user_id' => '5',
            ),
            1 =>
            array (
                'id' => 2,
                'order_number' => 'ERYARP20211231104433R2',
                'amount' => '110',
                'sub_total' => '110',
                'total_add_on' => '0',
                'total_shipping' => '8',
                'voucher_amount' => '0',
                'wallet_type' => '1',
                'receiver_name' => 'Test Merchant',
                'receiver_phone' => '6012345667',
                'receiver_address_1' => '11 aaa',
                'receiver_address_2' => NULL,
                'receiver_city' => 'Test City',
                'receiver_state' => 'Johor',
                'receiver_postcode' => '12345',
                'pre_point_balance' => '10000',
                'post_point_balance' => '9890',
                'collect_type' => '2',
                'tracking_code' => 'Thetrackingcode001',
                'shipout_at' => '2021-12-31 11:01:58',
                'pickup_at' => NULL,
                'completed_at' => '2021-12-31 11:03:49',
                'refund_at' => NULL,
                'status' => '5',
                'remark' => 'TESTING',
                'invoice_number' => 'INV-0000012/21',
                'created_at' => '2021-12-31 10:44:33',
                'updated_at' => '2021-12-31 11:03:49',
                'deleted_at' => NULL,
                'user_id' => '5',
                'payment_method_id' => '4',
                'pickup_location_id' => NULL,
                'shipped_by_id' => '2',
                'picked_up_by_id' => NULL,
                'completed_by_id' => '2',
                'refund_by_id' => NULL,
                'shipping_company_id' => '1',
                'invoice_user_id' => '5',
                'order_user_id' => '5',
            ),
            2 =>
            array (
                'id' => 3,
                'order_number' => 'ERYARP20211231111824R3',
                'amount' => '0',
                'sub_total' => '90',
                'total_add_on' => '0',
                'total_shipping' => '8',
                'voucher_amount' => '90',
                'wallet_type' => '3',
                'receiver_name' => 'Test Merchant',
                'receiver_phone' => '6012345667',
                'receiver_address_1' => '11 aaa',
                'receiver_address_2' => NULL,
                'receiver_city' => 'Test City',
                'receiver_state' => 'Johor',
                'receiver_postcode' => '12345',
                'pre_point_balance' => '10000',
                'post_point_balance' => '9910',
                'collect_type' => '2',
                'tracking_code' => NULL,
                'shipout_at' => NULL,
                'pickup_at' => NULL,
                'completed_at' => NULL,
                'refund_at' => '2021-12-31 11:19:32',
                'status' => '4',
                'remark' => 'Test Millionaire',
                'invoice_number' => NULL,
                'created_at' => '2021-12-31 11:18:24',
                'updated_at' => '2021-12-31 11:19:32',
                'deleted_at' => NULL,
                'user_id' => '5',
                'payment_method_id' => '4',
                'pickup_location_id' => NULL,
                'shipped_by_id' => NULL,
                'picked_up_by_id' => NULL,
                'completed_by_id' => NULL,
                'refund_by_id' => '2',
                'shipping_company_id' => NULL,
                'invoice_user_id' => '5',
                'order_user_id' => '5',
            ),
            3  =>
            array (
                'id' => 4,
                'order_number' => 'ERYARP20211231112128R4',
                'amount' => '220',
                'sub_total' => '220',
                'total_add_on' => '0',
                'total_shipping' => '0',
                'voucher_amount' => '0',
                'wallet_type' => '1',
                'receiver_name' => NULL,
                'receiver_phone' => NULL,
                'receiver_address_1' => NULL,
                'receiver_address_2' => NULL,
                'receiver_city' => NULL,
                'receiver_state' => NULL,
                'receiver_postcode' => NULL,
                'pre_point_balance' => '10000',
                'post_point_balance' => '9780',
                'collect_type' => '1',
                'tracking_code' => NULL,
                'shipout_at' => NULL,
                'pickup_at' => '2021-12-31 11:25:12',
                'completed_at' => '2021-12-31 11:27:37',
                'refund_at' => NULL,
                'status' => '5',
                'remark' => 'Test Executive Pickup',
                'invoice_number' => 'INV-0000013/21',
                'created_at' => '2021-12-31 11:21:28',
                'updated_at' => '2021-12-31 11:27:37',
                'deleted_at' => NULL,
                'user_id' => '5',
                'payment_method_id' => '4',
                'pickup_location_id' => '1',
                'shipped_by_id' => NULL,
                'picked_up_by_id' => '2',
                'completed_by_id' => '2',
                'refund_by_id' => NULL,
                'shipping_company_id' => NULL,
                'invoice_user_id' => '5',
                'order_user_id' => '5',
            ),
            4  =>
            array (
                'id' => 5,
                'order_number' => 'ERYARP20211231143056R5',
                'amount' => '100',
                'sub_total' => '100',
                'total_add_on' => '0',
                'total_shipping' => '8',
                'voucher_amount' => '0',
                'wallet_type' => '2',
                'receiver_name' => 'Test Merchant',
                'receiver_phone' => '6012345667',
                'receiver_address_1' => '11 aaa',
                'receiver_address_2' => NULL,
                'receiver_city' => 'Test City',
                'receiver_state' => 'Johor',
                'receiver_postcode' => '12345',
                'pre_point_balance' => '10000',
                'post_point_balance' => '9900',
                'collect_type' => '2',
                'tracking_code' => NULL,
                'shipout_at' => NULL,
                'pickup_at' => '2021-12-31 11:25:12',
                'completed_at' => '2021-12-31 11:27:37',
                'refund_at' => NULL,
                'status' => '1',
                'remark' => 'Testing Manager',
                'invoice_number' => NULL,
                'created_at' => '2021-12-31 14:30:56',
                'updated_at' => '2021-12-31 14:30:56',
                'deleted_at' => NULL,
                'user_id' => '5',
                'payment_method_id' => '4',
                'pickup_location_id' => NULL,
                'shipped_by_id' => NULL,
                'picked_up_by_id' => NULL,
                'completed_by_id' => NULL,
                'refund_by_id' => NULL,
                'shipping_company_id' => NULL,
                'invoice_user_id' => '5',
                'order_user_id' => '5',
            ),
        ));
    }
}
