<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('users')->delete();

        \DB::table('users')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'Test Merchant',
                'password' => '$2y$10$T2XHqmhfRxE9HZA2sfPeBudvZr8kexqei0ByW73Av0X.kCa3TDL0q', // Plaintext is "password"
                'identity_type' => NULL,
                'identity_no' => '',
                'phone' => '',
                'email' => 'merchant@merchant.com',
                'date_of_birth' => NULL,
                'gender' => NULL,
                'bank_name' => '',
                'bank_account_name' => '',
                'bank_account_number' => '',
                'user_type' => '3',
                'personal_code' => 'AZM6V',
                'status' => '2',
                'account_verify' => NULL,
                'ssm_verify' => NULL,
                'shop_verify' => NULL,
                'first_payment' => NULL,
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-09-13 13:06:40',
                'deleted_at' => NULL,
                'bank_list_id' => NULL,
                'country_id' => NULL,
//                'direct_upline_id' => 1,
//                'upline_user_id' => 1,
//                'upline_user_1_id' => 2,
//                'upline_user_2_id' => 3,
                'otp_code' => NULL,
                'register_verify_at' => NULL,
                'sign_agreement_at' => NULL,
                'sign_agreement_name' => NULL,
                'sign_agreement_identity' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'Test Merchant 2',
                'password' => '$2y$10$gSkHYbAEV2Iw62a16zXNw.O7owsqLR/COAfc2pquTbtYaieqdYsQi',
                'identity_type' => NULL,
                'identity_no' => '',
                'phone' => '',
                'email' => 'merchant2@merchant.com',
                'date_of_birth' => NULL,
                'gender' => NULL,
                'bank_name' => '',
                'bank_account_name' => '',
                'bank_account_number' => '',
                'user_type' => '3',
                'personal_code' => 'U4MJN',
                'status' => '2',
                'account_verify' => NULL,
                'ssm_verify' => NULL,
                'shop_verify' => NULL,
                'first_payment' => NULL,
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-09-13 13:06:40',
                'deleted_at' => NULL,
                'bank_list_id' => NULL,
                'country_id' => NULL,
//                'direct_upline_id' => 2,
//                'upline_user_id' => 2,
//                'upline_user_1_id' => 1,
//                'upline_user_2_id' => 3,
                'otp_code' => NULL,
                'register_verify_at' => NULL,
                'sign_agreement_at' => NULL,
                'sign_agreement_name' => NULL,
                'sign_agreement_identity' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'Test Merchant 3',
                'password' => '$2y$10$gIBvKZibR9KFS109cBYEcOLouY6i5MIUbBuTV6nRmQR5SJGlph3U2',
                'identity_type' => NULL,
                'identity_no' => '',
                'phone' => '',
                'email' => 'merchant3@merchant.com',
                'date_of_birth' => NULL,
                'gender' => NULL,
                'bank_name' => '',
                'bank_account_name' => '',
                'bank_account_number' => '',
                'user_type' => '3',
                'personal_code' => 'SKCFC',
                'status' => '2',
                'account_verify' => NULL,
                'ssm_verify' => NULL,
                'shop_verify' => NULL,
                'first_payment' => NULL,
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-09-13 13:06:40',
                'deleted_at' => NULL,
                'bank_list_id' => NULL,
                'country_id' => NULL,
//                'direct_upline_id' => 3,
//                'upline_user_id' => 3,
//                'upline_user_1_id' => 1,
//                'upline_user_2_id' => 2,
                'otp_code' => NULL,
                'register_verify_at' => NULL,
                'sign_agreement_at' => NULL,
                'sign_agreement_name' => NULL,
                'sign_agreement_identity' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'Lim Chiew Teng',
                'password' => '$2y$10$1rORx79z75LQijbp3AxhEea4N5zy1LR75GMLKhOf.rnwXMhy2AvBe',
                'identity_type' => '1',
                'identity_no' => '820903015566',
                'phone' => '60129199903',
                'email' => 'ricole_903@hotmail.com',
                'date_of_birth' => '1982-09-03',
                'gender' => '2',
                'bank_name' => 'MAYBANK',
                'bank_account_name' => 'Lim Chiew Teng',
                'bank_account_number' => '123456789',
                'user_type' => '3',
                'personal_code' => '9QH4Q',
                'status' => '2',
                'account_verify' => NULL,
                'ssm_verify' => NULL,
                'shop_verify' => NULL,
                'first_payment' => NULL,
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-09-13 13:09:07',
                'deleted_at' => NULL,
                'bank_list_id' => 1,
                'country_id' => NULL,
//                'direct_upline_id' => 1,
//                'upline_user_id' => 1,
//                'upline_user_1_id' => 2,
//                'upline_user_2_id' => 3,
                'otp_code' => NULL,
                'register_verify_at' => NULL,
                'sign_agreement_at' => NULL,
                'sign_agreement_name' => NULL,
                'sign_agreement_identity' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'name' => 'Melvin Lam',
                'password' => '$2y$10$1rORx79z75LQijbp3AxhEea4N5zy1LR75GMLKhOf.rnwXMhy2AvBe',
                'identity_type' => '1',
                'identity_no' => '970518011111',
                'phone' => '60177193728',
                'email' => 'lamfeng97@gmail.com',
                'date_of_birth' => '1997-05-18',
                'gender' => '1',
                'bank_name' => 'PUBLICBANK',
                'bank_account_name' => 'Lam Yi Feng',
                'bank_account_number' => '1234561111',
                'user_type' => '1',
                'personal_code' => 'LYF36',
                'status' => '1',
                'account_verify' => NULL,
                'ssm_verify' => NULL,
                'shop_verify' => NULL,
                'first_payment' => NULL,
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-12-28 18:00:00',
                'deleted_at' => NULL,
                'bank_list_id' => 9,
                'country_id' => NULL,
//                'direct_upline_id' => 1,
//                'upline_user_id' => 1,
//                'upline_user_1_id' => 2,
//                'upline_user_2_id' => 3,
                'otp_code' => '123456',
                'register_verify_at' => '2021-12-28 18:10:00',
                'sign_agreement_at' => NULL,
                'sign_agreement_name' => NULL,
                'sign_agreement_identity' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'name' => 'Melvin Yi',
                'password' => '$2y$10$1rORx79z75LQijbp3AxhEea4N5zy1LR75GMLKhOf.rnwXMhy2AvBe',
                'identity_type' => '1',
                'identity_no' => '970518012222',
                'phone' => '60177193728',
                'email' => 'yifeng97@gmail.com',
                'date_of_birth' => '1997-05-18',
                'gender' => '1',
                'bank_name' => 'PUBLICBANK',
                'bank_account_name' => 'Lam Yi Feng',
                'bank_account_number' => '1234562222',
                'user_type' => '2',
                'personal_code' => 'LYF66',
                'status' => '1',
                'account_verify' => NULL,
                'ssm_verify' => NULL,
                'shop_verify' => NULL,
                'first_payment' => NULL,
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-12-29 18:00:00',
                'deleted_at' => NULL,
                'bank_list_id' => 9,
                'country_id' => NULL,
//                'direct_upline_id' => 1,
//                'upline_user_id' => 1,
//                'upline_user_1_id' => 2,
//                'upline_user_2_id' => 3,
                'otp_code' => NULL,
                'register_verify_at' => NULL,
                'sign_agreement_at' => NULL,
                'sign_agreement_name' => NULL,
                'sign_agreement_identity' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'name' => 'Melvin Feng',
                'password' => '$2y$10$1rORx79z75LQijbp3AxhEea4N5zy1LR75GMLKhOf.rnwXMhy2AvBe',
                'identity_type' => '1',
                'identity_no' => '970518013333',
                'phone' => '60177193728',
                'email' => 'feng97@gmail.com',
                'date_of_birth' => '1997-05-18',
                'gender' => '1',
                'bank_name' => 'MAYBANK',
                'bank_account_name' => 'Lam Yi Feng',
                'bank_account_number' => '1234563333',
                'user_type' => '3',
                'personal_code' => 'LYF66',
                'status' => '1',
                'account_verify' => NULL,
                'ssm_verify' => NULL,
                'shop_verify' => NULL,
                'first_payment' => NULL,
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => '2021-12-30 18:00:00',
                'deleted_at' => NULL,
                'bank_list_id' => 1,
                'country_id' => NULL,
//                'direct_upline_id' => 1,
//                'upline_user_id' => 1,
//                'upline_user_1_id' => 2,
//                'upline_user_2_id' => 3,
                'otp_code' => NULL,
                'register_verify_at' => NULL,
                'sign_agreement_at' => NULL,
                'sign_agreement_name' => NULL,
                'sign_agreement_identity' => NULL,
            ),
        ));

        User::whereId(1)->update([
            'direct_upline_id' => 1,
            'upline_user_id' => 1,
            'upline_user_1_id' => 2,
            'upline_user_2_id' => 3,
        ]);
        User::whereId(2)->update([
            'direct_upline_id' => 2,
            'upline_user_id' => 2,
            'upline_user_1_id' => 1,
            'upline_user_2_id' => 3,
        ]);
        User::whereId(3)->update([
            'direct_upline_id' => 3,
            'upline_user_id' => 3,
            'upline_user_1_id' => 1,
            'upline_user_2_id' => 2,
        ]);
        User::whereId(4)->update([
            'direct_upline_id' => 1,
            'upline_user_id' => 1,
            'upline_user_1_id' => 2,
            'upline_user_2_id' => 3,
        ]);
        User::whereId(5)->update([
            'direct_upline_id' => 4,
            'upline_user_id' => 1,
            'upline_user_1_id' => 2,
            'upline_user_2_id' => 3,
        ]);
        User::whereId(6)->update([
            'direct_upline_id' => 4,
            'upline_user_id' => 5,
            'upline_user_1_id' => 2,
            'upline_user_2_id' => 3,
        ]);
        User::whereId(7)->update([
            'direct_upline_id' => 4,
            'upline_user_id' => 5,
            'upline_user_1_id' => 6,
            'upline_user_2_id' => 7,
        ]);

    }
}
